server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment_route
          #uri: lb://localhost:8001   cloud-payment-service
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/getPort

        - id: payment_route2
          #uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/getPort

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    #表示是否将自己注册进EurekaServer  默认为true
    service-url:
      register-with-eureka: true
        #是否从EurekaServer抓取已有的注册信息，默认为true 集群配合ribbon负载
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka
