server:
  port: 3344


eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lingsgit/cloud-config.git
          search-paths:
            - cloud-config
      label: master